data:
  # image: tianon/true:latest (docker/fig#919)
  image: busybox:latest
  volumes:
    - /data
    - /var/lib/postgresql/data
  entrypoint: /bin/echo

redis:
  image: redis:3.0
  volumes_from:
    - data
  restart: always

postgres:
  image: postgres:9.4
  volumes_from:
    - data
  restart: always

www:
  build: .
  ports:
    - "8080"
  links:
    - redis
    - postgres
  volumes_from:
    - data
  env_file:
    - private-data/environment.sh
  environment:
    - VIRTUAL_HOST=sentry.dnt.privat
    - VIRTUAL_PORT=8080
  command: sentry start --noinput
  restart: always

celery-beat:
  build: .
  links:
    - redis
    - postgres
  volumes_from:
    - data
  env_file:
    - private-data/environment.sh
  environment:
    - C_FORCE_ROOT=True
  command: sentry celery beat
  restart: always

celery-worker:
  build: .
  links:
    - redis
    - postgres
  volumes_from:
    - data
  env_file:
    - private-data/environment.sh
  environment:
    - C_FORCE_ROOT=True
  command: sentry celery worker
  restart: always
